apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-app
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://github.com/NikoGrid/NikoGrid.git
      targetRevision: monitoring
      path: infra/monitoring/loki
    - repoURL: https://grafana.github.io/helm-charts
      chart: loki
      targetRevision: "6.30.1"
      helm:
        valuesObject:
          loki:
            commonConfig:
              replication_factor: 1
            schemaConfig:
              configs:
                - from: "2024-04-01"
                  store: tsdb
                  object_store: filesystem
                  schema: v13
                  index:
                    prefix: loki_index_
                    period: 24h
            pattern_ingester:
              enabled: true
            limits_config:
              allow_structured_metadata: true
              volume_enabled: true
            ruler:
              enable_api: true
            storage:
              type: filesystem

          chunksCache:
            enabled: false

          deploymentMode: SingleBinary

          singleBinary:
            replicas: 1

          lokiCanary:
            enabled: false

          gateway:
            enabled: false

          test:
            enabled: false

          # Zero out replica counts of other deployment modes
          backend:
            replicas: 0
          read:
            replicas: 0
          write:
            replicas: 0

          ingester:
            replicas: 0
          querier:
            replicas: 0
          queryFrontend:
            replicas: 0
          queryScheduler:
            replicas: 0
          distributor:
            replicas: 0
          compactor:
            replicas: 0
          indexGateway:
            replicas: 0
          bloomCompactor:
            replicas: 0
          bloomGateway:
            replicas: 0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
