services:
  db:
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    image: "postgis/postgis:17-3.5-alpine"
    restart: always
    volumes:
      - "pgdata:/var/lib/postgresql/data"
      - "./backend/src/test/resources/dev-db-init.sql:/docker-entrypoint-initdb.d/extensions.sql"
    ports:
      - "5432:5432"

volumes:
  pgdata:
