apiVersion: v1
kind: Secret
metadata:
  name: loki-grafana-datasource
  labels:
    grafana_datasource: "1"
stringData:
  loki.yaml: |-
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        orgId: 1
        url: http://loki-app.monitoring:3100
        jsonData:
          httpHeaderName1: "X-Scope-OrgID"
        secureJsonData:
          httpHeaderValue1: "1"
