CREATE TABLE chargers
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    available   BOOLEAN                                 NOT NULL,
    max_power   FLOAT                                   NOT NULL,
    location_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_chargers PRIMARY KEY (id)
);

CREATE TABLE locations
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    lat  FLOAT                                   NOT NULL,
    lon  FLOAT                                   NOT NULL,
    geom GEOMETRY GENERATED ALWAYS AS (ST_Point(lon, lat, 4326)) STORED,
    CONSTRAINT pk_locations PRIMARY KEY (id)
);

ALTER TABLE chargers
    ADD CONSTRAINT FK_CHARGERS_ON_LOCATION FOREIGN KEY (location_id) REFERENCES locations (id);

CREATE INDEX locations_geom_idx
    ON locations
    USING GIST (geom);

CREATE INDEX chargers_location_id_idx ON chargers(location_id);