CREATE TABLE reservation
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    UUID                                    NOT NULL,
    charger_id BIGINT                                  NOT NULL,
    starts_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    ends_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,

    CONSTRAINT pk_reservation PRIMARY KEY (id),
    -- Constraint for checking that reservations do not overlap
    CONSTRAINT ec_working_hours_overlap EXCLUDE USING gist(
        charger_id WITH =,
        tsrange("starts_at", "ends_at", '[)') WITH &&
    )
);

ALTER TABLE reservation
    ADD CONSTRAINT FK_RESERVATION_ON_CHARGER FOREIGN KEY (charger_id) REFERENCES chargers (id) ON DELETE CASCADE;

ALTER TABLE reservation
    ADD CONSTRAINT FK_RESERVATION_ON_USER FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;