apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nikogrid.fullname" . }}-backend
  labels:
    {{- include "nikogrid.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "nikogrid.backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.backend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nikogrid.labels" . | nindent 8 }}
        {{- include "nikogrid.backend.selectorLabels" . | nindent 8 }}
        {{- with .Values.backend.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nikogrid.serviceAccountName" . }}
      {{- with .Values.backend.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.backend.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: SPRING_APPLICATION_JSON
              value: |
                {
                  "spring.profiles.active": "prod",
                  "spring.config.import": "configtree:/etc/config/",
                  "springdoc.api-docs.path": "/api/docs/v3",
                  "springdoc.swagger-ui.path": "/api/swagger-ui.html",
                  "springdoc.swagger-ui.url": "/api/docs/v3",
                  "springdoc.swagger-ui.configUrl": "/api/docs/v3/swagger-config",
                  "springdoc.swagger-ui.disable-swagger-default-url": true
                }
            - name: NIKOGRID_JWT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "nikogrid.fullname" . }}-secret
                  key: tokenSecret
          volumeMounts:
            - name: database-secret
              readOnly: true
              mountPath: "/etc/config/spring.datasource.url"
              subPath: jdbc-uri
            - name: database-secret
              readOnly: true
              mountPath: "/etc/config/spring.datasource.username"
              subPath: username
            - name: database-secret
              readOnly: true
              mountPath: "/etc/config/spring.datasource.password"
              subPath: password
            {{- with .Values.backend.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- if .Values.backend.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: {{ .Values.backend.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.backend.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.backend.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.backend.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.backend.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: {{ .Values.backend.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.backend.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.backend.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.backend.readinessProbe.failureThreshold }}
          {{- end }}
          {{- with .Values.backend.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: database-secret
          secret:
            secretName: {{ include "nikogrid.fullname" . }}-cluster-app
        {{- with .Values.backend.extraVolumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.backend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
