apiVersion: v1
kind: Service
metadata:
  name: {{ include "nikogrid.fullname" . }}-backend-svc
  labels:
    {{- include "nikogrid.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      protocol: TCP
      appProtocol: http
      port: 8080
      targetPort: http
  selector:
    {{- include "nikogrid.backend.selectorLabels" . | nindent 4 }}
